/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * EAS
 * The EAS API description
 * OpenAPI spec version: 0.1
 */

export interface CreateStudentDto {
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
}
