/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * EAS
 * The EAS API description
 * OpenAPI spec version: 0.1
 */
import type { RiskStudentsDetailEntity } from "./riskStudentsDetailEntity";

export interface PagedRiskStudentsDetail {
  total: number;
  items: RiskStudentsDetailEntity[];
}
