/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * EAS
 * The EAS API description
 * OpenAPI spec version: 0.1
 */
import type { FactorsConcernedEntity } from "./factorsConcernedEntity";

export interface RiskStudentsDetailEntity {
  riskStudentDetailsId: number;
  facultyName: string;
  facultyEmail: string;
  courseNumber: string;
  courseCrn: string;
  studentName: string;
  studentId: string;
  studentNetId: string;
  createdDate: string;
  updatedDate: string;
  isDeleted: boolean;
  notes: string;
  isGraduateStudent: boolean;
  graduateProgram: string;
  sendEmail?: boolean;
  FactorsConcerned: FactorsConcernedEntity[];
}
