/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * EAS
 * The EAS API description
 * OpenAPI spec version: 0.1
 */

export interface StudentEntity {
  ksuId: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  homeDepartment: string;
  major: string;
  gpa: string;
  cohort: string;
  academicStanding: string;
  createdDate: string;
  updatedDate: string;
  isDeleted: boolean;
}
